[project]
name = "s0_renamer"
version = "0.1.0"
description = "A Python project"
dependencies = []
[[project.authors]]
name = "lorenzinco"

[build-system]
requires = [ "setuptools >= 61.0",]
build-backend = "setuptools.build_meta"

[project.license]
file = "LICENSE"

[tool.setuptools.package-dir]
s0_renamer = "s0_renamer"
